[project]
name = "samhall_hackathon"
version = "0.1.0"
description = "Solution for workers scheduling"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.122.0",
    "pydantic-ai>=1.24.0",
    "python-magic>=0.4.27",
]
